### ISSUE TITLE
运行出错无法导入

### ISSUE THREAD

**Issue by edwardcuchulainn** [jarrett-au/douban2notion#2]
模板已经复制，依赖已经安装，对应的参数也填了进去，但在运行的时候，显示'NoneType' object has no attribute 'img'，请问是什么原因呢？
<img width="697" alt="image" src="https://user-images.githubusercontent.com/51317695/234750999-7ec768cf-5b90-463c-be80-d07557ec3d63.png">

**Comment by jarrett-au** [comment]
已经更新，请重新下载~
